export const salesData = [
  {
    product: "Breads",
    category: "Food & {br}Beverages",
    sales: "11.1",
    expectedSales: "10",
  },
  {
    product: "Juice",
    category: "Food & {br}Beverages",
    sales: "27.75",
    expectedSales: "30",
  },
  {
    product: "Noodles",
    category: "Food & {br}Beverages",
    sales: "9.99",
    expectedSales: "10",
  },
  {
    product: "Seafood",
    category: "Food & {br}Beverages",
    sales: "6.66",
    expectedSales: "10",
  },
  {
    product: "Sun Glasses",
    category: "Apparel &{br}Accessories",
    sales: "10.08",
    expectedSales: "10",
  },
  {
    product: "Clothing",
    category: "Apparel &{br}Accessories",
    sales: "18.9",
    expectedSales: "20",
  },
  {
    product: "Handbags",
    category: "Apparel &{br}Accessories",
    sales: "6.3",
    expectedSales: "5",
  },
  {
    product: "Shoes",
    category: "Apparel &{br}Accessories",
    sales: "6.72",
    expectedSales: "6",
  },
  {
    product: "Bath &{br}Grooming",
    category: "Baby {br}Products",
    sales: "9.45",
    expectedSales: "8",
  },
  {
    product: "Feeding",
    category: "Baby {br}Products",
    sales: "6.3",
    expectedSales: "6.3",
  },
  {
    product: "Diapers",
    category: "Baby {br}Products",
    sales: "6.3",
    expectedSales: "4",
  },
  {
    product: "Laptops",
    category: "Electronics",
    sales: "6.3",
    expectedSales: "5",
  },
  {
    product: "Televisions",
    category: "Electronics",
    sales: "10.5",
    expectedSales: "8",
  },
  {
    product: "SmartPhones",
    category: "Electronics",
    sales: "11.4",
    expectedSales: "13",
  },
];
